version: "3.1"

services:
  app:
    build:
      context: .
    environment:
      - DB_USER=${DB_USER}
      - PORT=5000
      - DB_HOST=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - REDIS_ADDR=redisdb:6379
    depends_on:
      postgres:
        condition: service_healthy
      redisdb:
        condition: service_healthy
    ports:
      - 5000:5000
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  redisdb:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
